In [ ]:
#Варіант 7

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [ ]:
#Завдання 1. Створіть одновимірний масив (вектор) зі сходячою послідовністю чисел, де кожне наступне число більше попереднього на 3, починаючи з 5, та виведіть його значення.
poch = 5
dovj = 20
a = np.arange(poch, poch + dovj * 3, 3)
print(a)

[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62]


In [ ]:
#Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його добутками квадратів кожного числа та його подвійного значення, починаючи з 1, та виведіть його значення.
poch = 1
m = (3, 3)
a = np.arange(poch, poch + m[0] * m[1])
a = a.reshape(m)
a = (a ** 2) * (2 * a)
print(a)

[[0.0743922  1.69096836 0.30568829]
 [0.07217099 0.52645666 0.60691934]
 [0.75313333 0.07627055 0.17425311]]


In [ ]:
#Завдання 3. Створіть масив розміром 10x10, заповніть його випадковими дійсними числами в діапазоні від -50 до 50 та виведіть його значення.
m = (10, 10)
a = np.random.randint(-50, 50, m)
print (a)

[[ 46  48 -15  36   2  20 -18  -3  42 -20]
 [-47 -39  -9 -46  35  16 -36 -45  -5 -27]
 [-11   8  45  -7  -8 -49  19  26 -14  -6]
 [-10  45   6 -13 -13  48  48  33 -45  25]
 [  0  17  29 -27  33  -2   0  39  31  42]
 [ -2  37 -20 -47  23  12   5  -5  43 -32]
 [-47 -27   7 -25 -31  12 -45  15 -36 -34]
 [-19  29 -43   2  44 -28  45  -5  43 -22]
 [ 41  18 -13   0  49 -35 -47  34  40 -26]
 [ 44 -10  -5  21  35 -10 -45 -13 -38 -34]]


In [ ]:
#Завдання 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить середнє значення елементів кожного стовпця матриці.
m = (4, 4)
a = np.random.uniform(0, 1, m)
c = np.mean(a, axis=0)
print (c)

[0.47415159 0.65553848 0.21520958 0.44063699]


In [ ]:
#Завдання 5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними числами від -2.5 до 2.5 та виконайте на них поелементні операції додавання, віднімання та множення.
dovj = 7
poch = -2.5
kinec = 2.5
a1= np.random.randint(poch, kinec, dovj)
a2= np.random.randint(poch, kinec, dovj)
dodav = a1 + a2
vidn = a1 - a2
mnoz = a1 * a2
print("Додавання:", dodav)
print("Віднімання:", vidn)
print("Множення:", mnoz)

Додавання: [-3  0 -1 -3  2  1 -2]
Віднімання: [-1  2  3 -1  0  1  0]
Множення: [ 2 -1 -2  2  1  0  1]


In [5]:
#Завдання 6. Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.
v1 = np.array([4, 6, 1, 12, 16, 1, 9])
v2 = np.array([8, 5, 29, 4, 1, 6, 2])
s = np.dot(v1, v2)
print(s)

179


In [27]:
#Завдання 7. Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
r1 = (4, 2)
r2 = (2, 2)
m1 = np.random.randint(1, 10, r1)
m2 = np.random.randint(1, 10, r2)
mnoz = np.dot(m1, m2)
print(mnoz)

[[15 32]
 [23 74]
 [30 64]
 [24 38]]


In [11]:
#Завдання 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
r = (2, 2)
m = np.random.randint(1, 12, r)
print(m)
m2 = np.linalg.inv(m)
print(m2)
#Невпевнений у правильності рішення

[[8 3]
 [4 8]]
[[ 0.15384615 -0.05769231]
 [-0.07692308  0.15384615]]


In [26]:
#Завдання 9. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.
r = (3, 3)
m = np.random.randint(0, 2, r)
t = np.transpose(m)
print(t)
#Якщо написати (0, 1) будуть лише нулі. Я не зрозумів включно тут чи ні. Так само і в 7 та 8 завданнях.

[[1 1 0]
 [0 0 0]
 [1 1 1]]


In [25]:
#Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть від'ємні елементи отриманої матриці.
r1 = (3, 4)
r2 = (4)
m = np.random.randint(1, 10, r1)
v = np.random.randint(1, 10, r2)
minusM = m[m<0]
minusV = v[v<0]
print(minusM)
print(minusV)
#Чи повинні вони бути порожніми? Ми же створили матрицю і вектор з додатними числами.

[]
[]


In [31]:
#Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
r1 = (2,3)
r2 = (3)
m = np.random.randint(0, 2, r1)
v = np.random.randint(1, 10, r2)
dob = np.dot(m, v)
print(dob)

[ 8 11]
[[1 1 0]
 [1 1 1]]
[3 5 3]


In [32]:
#Завдання 12. Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю елементів першої матриці.
r = (8, 8)
m1 = np.random.randint(1, 10, r)
m2 = np.random.randint(1, 10, r)
riz = m1 - m2
print(riz)

[[ 4 -8 -4  4  8 -1  4 -6]
 [ 8 -3 -1 -1  0 -6  0 -2]
 [-6  2 -1  4  4  2  5  5]
 [ 0  5  5  3  2 -4  1  1]
 [ 1  0  0  0  3 -4 -2 -2]
 [-5  2 -1 -6  1  4 -1  1]
 [ 1 -7 -7 -1  3  1  3  5]
 [-2 -5  1  1 -2  3  1 -1]]


In [33]:
#Завдання 13. Створіть дві матриці розміром 8x8, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть різницю їх елементів.
r = (8, 8)
m1 = np.random.randint(-1, 1, r)
m2 = np.random.randint(-1, 1, r)
riz = m1 - m2
print(riz)

[[-1  0  1 -1  1  1 -1  0]
 [ 1  1 -1  0  0  1  1 -1]
 [ 1  0 -1 -1  1  1  0  1]
 [-1  0  0 -1 -1 -1  1  1]
 [ 1  0  0  0  0  0 -1  0]
 [ 0  0  0  1 -1  0  0 -1]
 [-1  1  0  0  0 -1 -1  1]
 [ 0  0  1 -1  0 -1  1  0]]


In [38]:
#Завдання 14. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє арифметичне значення елементів матриці.
r = (5, 5)
m = np.random.randint(0, 2, r)
a = np.mean(m)
print(a)

[[0 0 0 0 1]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 1 1 1]
 [0 1 1 0 0]]
0.32


In [45]:
#Завдання 15. Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем значення елементу у кожному рядку матриці.
r = (9, 9)
m = np.random.uniform(-0.5, 0.5, r)
max = np.max(m, axis = 1)
print(max)

[0.40828238 0.11150919 0.35513035 0.3762759  0.4297291  0.13266472
 0.45887037 0.43168066 0.42479738]


In [ ]:
#Висновок. В ції практичній роботі я навчився використовувати елементи лінійної алгебри в середовищі Python. За допомогою бібліотек Pandas та Numpy ми створювали діапазони значень(матриці та вектори) та здійснювали різноманітні операції з цими структурами даних.